### ISSUE TITLE
Login/Register with Google

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#19]

**Comment by omisteck** [comment]
Can this Issue be assign to me?

**Comment by Zelig880** [comment]
I have provided you priviledges now to allow you to assign the story to yourself!

also, join the slack channel (link in the readme), so that it is easier to chat!

**Comment by Zelig880** [comment]
Hei @omisteck  any progress on this stories?

**Comment by abhishek-bodapati** [comment]
Hi @omisteck, if there isn't any progress can I work on this?

**Comment by Zelig880** [comment]
It is OK, I think you can work on it. I tried to reach out a couple of
times but he seem busy..

**Comment by Zelig880** [comment]
This has been completed now
