### ISSUE TITLE
Modify bookshelf table

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#22]
Due to recent changes in the app, the following modification need to be implemented:

- Remove the column "pickup_times",
- Add a column called "opening_days" (this will be an array of number, that if i am not mistaken is just string in mysql)
- Add a column called "opening_hours" (this will be an array of number, that if i am not mistaken is just string in mysql)
- Modify the factory seeder to make sure that it it works as expected
- Change the "fillable" entry in the bookshelf.php file

**Comment by J-hon** [comment]
@Zelig880 
To which table should the "pickup_times" column be removed, "opening_days" and "opening_hours" columns be added?
