### ISSUE TITLE
Add user address

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#23]
As a user I would like to be able to record my Address into the Bookshelf Table so that it will be easy to fetch and use during the use of my app:

To do:
- [x] Add the following column in the Bookshelf table (Address Line 1, City, postcode) 
- [x] Make the correct modification within the Bookshelf.php file (fillable)
- [x] Make the correct changes to the seeder factory, to make sure that this info is filled when the database is created for dev purposes
- [x] Rename the current ManagementController within the Bookshelf folder to BookshelfItemManagementController
- [x] Create an API endpoint that will allow to update the above table 
- [x] Create a controller to handle the data modification (Bookshelf/BookshelfManagementController)
- [ ] Make sure to update the app with the new name (i think just the API endpoints need to)

**Comment by J-hon** [comment]
@Zelig880 Sorry but what do you mean by the last todo item?
