### ISSUE TITLE
compile errors after running npm run dev

### ISSUE THREAD

**Issue by sosualfred** [Zelig880/BooksBank#28]
![1 bug](https://user-images.githubusercontent.com/22264939/115109884-fc672c80-9f67-11eb-9e16-536dfcd9c2fa.png)
![2nd bug](https://user-images.githubusercontent.com/22264939/115109896-0852ee80-9f68-11eb-9b44-0a9707e8313d.png)

**Comment by sosualfred** [comment]
@Zelig880 Kindly, take a look at this.

**Comment by Zelig880** [comment]
Yes, I am going to look at it later today.

**Comment by Zelig880** [comment]
Hei @sosualfred ...

The app worked on for me and other people but i noticed some case miss-match between file names and import.

Can you please pull "main" again and let me know if there is any further issues

**Comment by sosualfred** [comment]
Hello @Zelig880

The app compiled this time around with 2 compilation errors instead of the previous 5.

Below is a screenshot of the two errors I got after running ```npm run watch```

![image](https://user-images.githubusercontent.com/22264939/115128113-079f7400-9fcb-11eb-8a1f-20501ff37873.png)

**Comment by sosualfred** [comment]
@Zelig880 I went ahead and changed the names(LendTimeslot and BorrowTimeslot) in index.js and the compilation was successful.

The issue I am facing now is: I get a blank page whenever I open the website.

![image](https://user-images.githubusercontent.com/22264939/115128365-ef305900-9fcc-11eb-848d-de8e78212cd5.png)

![image](https://user-images.githubusercontent.com/22264939/115128376-ffe0cf00-9fcc-11eb-802a-c22fc92b483e.png)

**Comment by sosualfred** [comment]
Surprisingly, I am able to see the homepage as well as the other pages now.  :laughing: 

![image](https://user-images.githubusercontent.com/22264939/115129834-18ef7d00-9fd9-11eb-8efe-9ffecb7b67e9.png)
