### ISSUE TITLE
Send email to confirm that book has been picked up

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#51]
As an user I would like to receive an email asking me if the books has been picked up at the expected time:

- [x] Create a cron job that run every day at 12 PM gmt (Midday)
- [x] Check if there is any book in AwaitingPickup and if the time is BEFORE now
- [x] Create a new email that includes the book name, and a button to confirm if pickup has been completed or reject
- [ ] Create endpoints (that require auth) to accept Pickup (move the ledge into a status of in progress, or reject ( mark the book ledge as rejected).

**Comment by J-hon** [comment]
@Zelig880 
There's already an endpoint to accept and reject the pickup of a book: 

"http://www.localhost:8000/api/ledge/request/respond/{{ $ledge->id }}"

**Comment by Zelig880** [comment]
Yes, the endpoint exist, it was created in another pr...
