### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#52]
As an user I would like the website to have an actual favicon, so that the image shown next to the website name in the browser tab is nice and distinctive.

- [ ] Take library icon of the website logo and save it as an image
- [ ] Create all required favicon sizes using a favicon generator from internet
- [ ] Add the favicon in the site and make sure the favicon link is the same within the public/index.php file ( or just check if you can see the new favicon when loading the website locally).

**Comment by Evavic44** [comment]
> As an user I would like the website to have an actual favicon, so that the image shown next to the website name in the browser tab is nice and distinctive.
> 
> * [ ]  Take library icon of the website logo and save it as an image
> * [ ]  Create all required favicon sizes using a favicon generator from internet
> * [ ]  Add the favicon in the site and make sure the favicon link is the same within the public/index.php file ( or just check if you can see the new favicon when loading the website locally).

![link looks ok](https://user-images.githubusercontent.com/62628408/118424328-f5dee880-b6be-11eb-8189-5b22e5690424.png)
Website already has a favicon.

**Comment by Zelig880** [comment]
hm.. I think that is my website not Booksbank! :) 

Also, the favicon should be the little bookshelf that is part of the logo..if you need me to actually provide the image I am happy to do so..

THis is the production site: http://booksbank.co.uk/

**Comment by Evavic44** [comment]
> hm.. I think that is my website not Booksbank! :) 
> 
> Also, the favicon should be the little bookshelf that is part of the logo..if you need me to actually provide the image I am happy to do so..
> 
> THis is the production site: http://booksbank.co.uk

Oh... I get. Yes if you can, please provide it so I can add it.

**Comment by Zelig880** [comment]
Do the following:

![image](https://user-images.githubusercontent.com/9040770/118473867-59d6d080-b702-11eb-94e9-512344cd7c90.png)

**Comment by Zelig880** [comment]
using this files: 
[favicon_package_v0.16.zip](https://github.com/Zelig880/BooksBank/files/6493166/favicon_package_v0.16.zip)

**Comment by abhishek-bodapati** [comment]
Hi, @Zelig880 I'm new to open source contributions. Can I work on this issue?

**Comment by Evavic44** [comment]
> Hi, @Zelig880 I'm new to open source contributions. Can I work on this issue?

I guess you can, didn't fix this because I couldn't find the `html` file.

**Comment by Zelig880** [comment]
@Evavic44 @abhishek-bodapati first time first serve on open source! Also I will create more small tasks like this..

The index file is in the public folder. Also next time you guys get stuck, just reach out and I can help

**Comment by Evavic44** [comment]
> @Evavic44 @abhishek-bodapati first time first serve on open source! Also I will create more small tasks like this..
> 
> The index file is in the public folder. Also next time you guys get stuck, just reach out and I can help

![IMG_20210520_212525.jpg](https://user-images.githubusercontent.com/62628408/119044412-0f7b7b00-b9b2-11eb-97e7-9f314da53ffa.jpg)
Oh this file? Haven't really worked on a PHP file before. Honestly, I don't know what I'm looking at. Is to to be added at the top before the <?php?

**Comment by Zelig880** [comment]
sorry i gave you the wrong link.. the favicon goes here: `resources\views\spa.blade.php`
