### ISSUE TITLE
Enable user to go back into the process while adding a book

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#54]
At the moment, an user is not able to go back while adding a book, and is forces to refresh the page to be able to add a new book (for example if they clicked on teh wrong title).

- [ ] Add a button on the bottom right of as shown in the attached picture if the add to your bookshelf is shown
- [ ] SHow the button only if a title has been selected from the dropdow
- [ ] Name the button "Start again" and use secondary theme
- [ ] When the button is clicked, cleanup the selected book variable and make sure the form is reset to its initial state
![image](https://user-images.githubusercontent.com/9040770/118355101-3119d400-b566-11eb-8b13-31f316a9a5bd.png)

**Comment by venkivijay** [comment]
@Zelig880 I have raised PR #59 for this issue. Please review it.

I used refs to access searchText and clear it as the Button triggering the reset and BookshelfAddStep1 components are Siblings.
