### ISSUE TITLE
Clear searchedBooks when an user navigates away from add page

### ISSUE THREAD

**Issue by venkivijay** [Zelig880/BooksBank#58]
At the moment, when a user searches for books on the bookshelf/add page, books are listed in the dropdown. But if the user navigates away from the bookshelf/add page without selecting a book, selectedBooks data is not cleared resulting in the dropdown being visible when the user again comes to bookshelf/add page.

Steps to reproduce:

- Click on "Add a book"
- Search for a book
- Navigate to any other page (click on the logo)
- Then again click on "Add a book"

Expected behavior:

- Dropdown should not be visible

**Comment by abhishek-bodapati** [comment]
Hi, can I work on this issue?

**Comment by Zelig880** [comment]
yes, go ahead and work on it.. if you have issues just reach out!

**Comment by abhishek-bodapati** [comment]
I think the issue can be closed now..!!

**Comment by venkivijay** [comment]
Closing this issue as it is resolved now.
