### ISSUE TITLE
Make "domain" used in email Dynamic from where email are sent from

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#80]
As a developer, I would like the link included within the emails to be dynamic and include the domain of the website used to send the email from.

NOTE: You can use the environment variable called "APP_URL" to define the website host.

- [ ] Update all EMAILS in the views/mail folder to use the above environment to generate the URL instead than hardcoded localhost

```
Example.. If i send it locally from localhost:8080 then a link will be Localhost:8080/book/request/1

If i send the email from production the link will be Booksbank.co.uk/book/request/1
```

**Comment by Zelig880** [comment]
@abhishek-bodapati this seem like a nice story for you if you want something easy to do! :)

**Comment by abhishek-bodapati** [comment]
> @abhishek-bodapati this seem like a nice story for you if you want something easy to do! :)
> 

Yeah I will do this!!
Thanks for letting me know😊!!

**Comment by abhishek-bodapati** [comment]
> As a developer, I would like the link included within the emails to be dynamic and include the domain of the website used to send the email from.
> 
> NOTE: You can use the environment variable called "APP_URL" to define the website host.
> 
> * [ ]  Update all EMAILS in the views/mail folder to use the above environment to generate the URL instead than hardcoded localhost
> 
> ```
> Example.. If i send it locally from localhost:8080 then a link will be Localhost:8080/book/request/1
> 
> If i send the email from production the link will be Booksbank.co.uk/book/request/1
> ```

I have to replace these links with the APP_URL, right?

![img](https://user-images.githubusercontent.com/47183749/120204311-4b320280-c246-11eb-8ec5-a6fcd6d8239b.jpeg)
