### ISSUE TITLE
Change items returned by the ledges enpoint to descending order

### ISSUE THREAD

**Issue by Zelig880** [Zelig880/BooksBank#91]
Current:
The order of the items received from the api request `https://booksbank.co.uk/api/ledge` are in ascending order

Expected
The order of the item is received on descending order

**Comment by kalig0** [comment]
I'd like to contribute to this.

**Comment by Zelig880** [comment]
Go ahead, they are all free unless people write on it! :)

**Comment by Zelig880** [comment]
any news @kalig0 ?
